version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "17:30"
      timezone: America/Vancouver
    open-pull-requests-limit: 10
    reviewers:
      - qjack001
    assignees:
      - qjack001
    commit-message:
      prefix: Update imports 
      include: scope
    labels:
      - "dependencies"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "17:30"
      timezone: America/Vancouver
    open-pull-requests-limit: 10
    reviewers:
      - qjack001
    assignees:
      - qjack001
    commit-message:
      prefix: Update imports 
      include: scope
    labels:
      - "dependencies"